name: caddy
services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    restart: unless-stopped
    env_file:
      - caddy.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Main Entry Point (Repo-managed)
      - ./configs/Caddyfile:/etc/caddy/Caddyfile:ro
      # Modular Site Blocks (Repo-managed)
      - ./configs/sites:/etc/caddy/sites:ro
      # Caddy Internal State (System-managed)
      - /srv/app-configs/caddy/data:/data
      - /srv/app-configs/caddy/config:/config
