services:
  freeipa:
    image: freeipa/freeipa-server:rocky-9
    container_name: freeipa-server
    hostname: auth.hacker-haus.org # IMPORTANT: Change this to your desired hostname
    command:
      - "--unattended"
      - "--realm=HACKER-HAUS.ORG" # IMPORTANT: Change this to your desired Kerberos realm (usually your domain in uppercase)
      - "--domain=hacker-haus.org" # IMPORTANT: Change this to your desired domain
      - "--ds-password=${IPA_ADMIN_PASSWORD}"
      - "--admin-password=${IPA_ADMIN_PASSWORD}"
      - "--ip-address=127.0.0.1" # Adjust if you have a specific IP to bind to
      - "--no-forwarders"
#      - "--setup-dns"
#      - "--no-dnssec-validation"
    environment:
      - IPA_SERVER_HOSTNAME=auth.hacker-haus.org # IMPORTANT: Must match the hostname above
      - PASSWORD=${IPA_ADMIN_PASSWORD} # Sets the password for 'admin' and the Directory Manager
    ports:
      # Standard Ports
      - "85:80"    # HTTP
      - "445:443"  # HTTPS
      - "389:389"  # LDAP
      - "636:636"  # LDAPS
      # Kerberos Ports
      - "88:88"    # Kerberos
      - "464:464"  # Kerberos kpasswd
      - "88:88/udp"
      - "464:464/udp"
      # DNS Port
 #     - "53:53/udp"
 #     - "53:53/tcp"
      # NTP Port
      - "123:123/udp"
    volumes:
      - /srv/app-configs/freeipa/data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    tty: true
    stdin_open: true

