---
services:
  radicale:
    image: tomsquest/docker-radicale:latest
    user: root
    ports:
      - "5232:5232"
    volumes:
      - /srv/app-configs/radicale/config:/config:ro
      - /srv/app-configs/radicale/data:/data
    restart: unless-stopped